# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lion
tagline: A Jekyll theme built with Bourbon, Bitters, Neat and Refills. So you know its good.
email: your-email@domain.com
heroicon: logo.svg
navicon: logo.svg
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#social media
twitter_username: jekyllrb

github_username:  jekyll
#github profile
github: www.github.com/
#facebook profile
facebook: www.facebook.com/
#reddit profile
reddit: www.reddit.com/
#twitter profile
twitter: www.twitter.com/
#google plus profile
googleplus: www.googleplus.com/
#dribble profile
dribble: www.dribble.com/
#Linkedin profile
linkedin: 
#instagram profile
instagram:
#pinterest profile
pinterest:
#codepen profile
codepen:
#tunblr profile
tumblr:
#vine profile
vine:

# Build settings
markdown: kramdown

gems: [bourbon, neat]

sass:
    sass_dir: _sass
    
excerpt_separator: ""


prefixbox:
  filename: "/prefixbox.csv" #the output filename 
  exclude:  # List of files to exclude from the search results
    -atom.xml
    -feed.xml
  include: # List of files you want to explicitly include as posts
